---
- name: nginx installation
  hosts: jenk
  ignore_errors: yes
  tasks:
    - name: install epel-release
      yum: 
        name: epel-release
        state: present
    - name: install nginx
      yum:
        name: nginx
        state: present
   
    - name: start nginx
      service:
        name: nginx
        state: started
    - name: enable configuration
      service:
        name: nginx
        enabled: yes
    - name: copy index.html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0644
    - name: restart nginx
      service:
        name: nginx
        state: restarted


